apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dec4iot-tls
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  secretName: dec4iot-tls
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
  - 'dec4iot.data-container.net'